/* Generated By:JJTree&JavaCC: Do not edit this line. ObjectDbClauseParserConstants.java */
package org.uwcs.choob.support;

public interface ObjectDbClauseParserConstants {

  int EOF = 0;
  int P_FLOATVALUE = 4;
  int P_INTVALUE = 5;
  int P_TEXTVALUE = 6;
  int P_NAME = 7;
  int K_WHERE = 8;
  int K_SORT = 9;
  int K_LIMIT = 10;
  int K_WITH = 11;
  int K_FROM = 12;
  int K_SET = 13;
  int K_TABLE = 14;
  int K_INTO = 15;
  int K_SELECT = 16;
  int K_INSERT = 17;
  int K_DELETE = 18;
  int K_UPDATE = 19;
  int OPENBRACKET = 20;
  int CLOSEBRACKET = 21;
  int K_NOT = 22;
  int K_AND = 23;
  int K_OR = 24;
  int K_ASC = 25;
  int K_DESC = 26;
  int K_INTEGER = 27;
  int K_RANDOM = 28;
  int K_AS = 29;
  int K_0FUNC = 30;
  int K_1FUNC = 31;
  int K_2FUNC = 32;
  int K_3FUNC = 33;
  int K_LESS = 34;
  int K_GREATER = 35;
  int K_EQUAL = 36;
  int K_NOTEQUAL = 37;
  int K_RLIKE = 38;
  int K_LIKE = 39;
  int K_ADD = 40;
  int K_SUBTRACT = 41;
  int K_MULTIPLY = 42;
  int K_DIVIDE = 43;
  int COMMA = 44;
  int K_ISINT = 45;
  int K_ISFLOAT = 46;
  int K_ISSTR = 47;
  int K_ISBOOL = 48;
  int IDNAME = 49;
  int FIELDNAME = 50;
  int TEXTVALUE = 51;
  int FLOATVALUE = 52;
  int INTVALUE = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "<P_FLOATVALUE>",
    "<P_INTVALUE>",
    "<P_TEXTVALUE>",
    "<P_NAME>",
    "\"WHERE\"",
    "<K_SORT>",
    "\"LIMIT\"",
    "\"WITH\"",
    "\"FROM\"",
    "\"SET\"",
    "\"TABLE\"",
    "\"INTO\"",
    "\"SELECT\"",
    "\"INSERT\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"(\"",
    "\")\"",
    "<K_NOT>",
    "<K_AND>",
    "<K_OR>",
    "<K_ASC>",
    "<K_DESC>",
    "\"INTEGER\"",
    "<K_RANDOM>",
    "\"AS\"",
    "\"COUNT\"",
    "\"SUM\"",
    "\"SPAMANDEGGS\"",
    "\"CONCAT\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"!=\"",
    "<K_RLIKE>",
    "\"LIKE\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"ISINT\"",
    "\"ISFLOAT\"",
    "<K_ISSTR>",
    "\"ISBOOL\"",
    "<IDNAME>",
    "<FIELDNAME>",
    "<TEXTVALUE>",
    "<FLOATVALUE>",
    "<INTVALUE>",
  };

}
