/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeAdd.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeAdd extends SimpleNode {
  public ObjectDBClauseNodeAdd(int id) {
    super(id);
  }

  public ObjectDBClauseNodeAdd(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
