/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeField.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeField extends SimpleNode {
  public ObjectDBClauseNodeField(int id) {
    super(id);
  }

  public ObjectDBClauseNodeField(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
