/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeFieldSetList.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeFieldSetList extends SimpleNode {
  public ObjectDBClauseNodeFieldSetList(int id) {
    super(id);
  }

  public ObjectDBClauseNodeFieldSetList(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
