/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeRoot.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeRoot extends SimpleNode {
  public ObjectDBClauseNodeRoot(int id) {
    super(id);
  }

  public ObjectDBClauseNodeRoot(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
