/* Generated By:JJTree: Do not edit this line. org/uwcs/choob/support//ObjectDbClauseParserTreeConstants.java */

package org.uwcs.choob.support;

public interface ObjectDbClauseParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTROOT = 1;
  public int JJTADD = 2;
  public int JJTMUL = 3;
  public int JJTCONSTANT = 4;
  public int JJTFIELD = 5;


  public String[] jjtNodeName = {
    "void",
    "Root",
    "Add",
    "Mul",
    "Constant",
    "Field",
  };
}
