/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeConstant.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeConstant extends SimpleNode {
  public ObjectDBClauseNodeConstant(int id) {
    super(id);
  }

  public ObjectDBClauseNodeConstant(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
