/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeExpressionList.java */

package org.uwcs.choob.support;

public class ObjectDBClauseNodeExpressionList extends SimpleNode {
  public ObjectDBClauseNodeExpressionList(int id) {
    super(id);
  }

  public ObjectDBClauseNodeExpressionList(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
