/**
 * ChoobConnectionWrapper.
 * @author James Ross
 */
package uk.co.uwcs.choob.support;
import java.sql.*;
import java.util.*;

public final class ChoobConnectionWrapper implements Connection
{
	Connection conn;
	
	static void logSQL(String sql) {
		System.out.println(System.currentTimeMillis() + " " + sql);
	}
	
	public ChoobConnectionWrapper(Connection conn) {
		this.conn = conn;
	}
	
	public void clearWarnings() throws SQLException {
		conn.clearWarnings();
	}
	
	public void close() throws SQLException {
		conn.close();
	}
	
	public void commit() throws SQLException {
		conn.commit();
	}
	
	public Statement createStatement() throws SQLException {
		return new ChoobStatementWrapper(conn.createStatement());
	}
	
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return new ChoobStatementWrapper(conn.createStatement(resultSetType, resultSetConcurrency));
	}
	
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new ChoobStatementWrapper(conn.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
	}
	
	public boolean getAutoCommit() throws SQLException {
		return conn.getAutoCommit();
	}
	
	public String getCatalog() throws SQLException {
		return conn.getCatalog();
	}
	
	public int getHoldability() throws SQLException {
		return conn.getHoldability();
	}
	
	public DatabaseMetaData getMetaData() throws SQLException {
		return conn.getMetaData();
	}
	
	public int getTransactionIsolation() throws SQLException {
		return conn.getTransactionIsolation();
	}
	
	public Map<String,Class<?>> getTypeMap() throws SQLException {
		return conn.getTypeMap();
	}
	
	public SQLWarning getWarnings() throws SQLException {
		return conn.getWarnings();
	}
	
	public boolean isClosed() throws SQLException {
		return conn.isClosed();
	}
	
	public boolean isReadOnly() throws SQLException {
		return conn.isReadOnly();
	}
	
	public String nativeSQL(String sql) throws SQLException {
		return conn.nativeSQL(sql);
	}
	
	public CallableStatement prepareCall(String sql) throws SQLException {
		logSQL(sql);
		return conn.prepareCall(sql);
	}
	
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		logSQL(sql);
		return conn.prepareCall(sql, resultSetType, resultSetConcurrency);
	}
	
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		logSQL(sql);
		return conn.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql);
	}
	
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql, autoGeneratedKeys);
	}
	
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql, columnIndexes);
	}
	
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql, resultSetType, resultSetConcurrency);
	}
	
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		logSQL(sql);
		return conn.prepareStatement(sql, columnNames);
	}
	
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		conn.releaseSavepoint(savepoint);
	}
	
	public void rollback() throws SQLException {
		conn.rollback();
	}
	
	public void rollback(Savepoint savepoint) throws SQLException {
		conn.rollback(savepoint);
	}
	
	public void setAutoCommit(boolean autoCommit) throws SQLException {
		conn.setAutoCommit(autoCommit);
	}
	
	public void setCatalog(String catalog) throws SQLException {
		conn.setCatalog(catalog);
	}
	
	public void setHoldability(int holdability) throws SQLException {
		conn.setHoldability(holdability);
	}
	
	public void setReadOnly(boolean readOnly) throws SQLException {
		conn.setReadOnly(readOnly);
	}
	
	public Savepoint setSavepoint() throws SQLException {
		return conn.setSavepoint();
	}
	
	public Savepoint setSavepoint(String name) throws SQLException {
		return conn.setSavepoint(name);
	}
	
	public void setTransactionIsolation(int level) throws SQLException {
		conn.setTransactionIsolation(level);
	}
	
	public void setTypeMap(Map<String,Class<?>> map) throws SQLException {
		conn.setTypeMap(map);
	}
}
