/* Generated By:JJTree: Do not edit this line. uk/co/uwcs/choob/support/ObjectDbClauseParserTreeConstants.java */

package uk.co.uwcs.choob.support;

public interface ObjectDbClauseParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTROOT = 1;
  public int JJTADD = 2;
  public int JJTMUL = 3;
  public int JJTFUNCTION = 4;
  public int JJTCONSTANT = 5;
  public int JJTFIELD = 6;
  public int JJTEXPRESSIONLIST = 7;
  public int JJTFIELDSET = 8;
  public int JJTFIELDSETLIST = 9;


  public String[] jjtNodeName = {
    "void",
    "Root",
    "Add",
    "Mul",
    "Function",
    "Constant",
    "Field",
    "ExpressionList",
    "FieldSet",
    "FieldSetList",
  };
}
