/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeFunction.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeFunction extends SimpleNode {
  public ObjectDBClauseNodeFunction(int id) {
    super(id);
  }

  public ObjectDBClauseNodeFunction(ObjectDbClauseParser p, int id) {
    super(p, id);
  }

}
