/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeFieldSet.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeFieldSet extends SimpleNode {
	public ObjectDBClauseNodeFieldSet(int id) {
		super(id);
	}

	public ObjectDBClauseNodeFieldSet(ObjectDBClauseParser p, int id) {
		super(p, id);
	}

}
