/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeField.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeField extends SimpleNode {
	public ObjectDBClauseNodeField(int id) {
		super(id);
	}

	public ObjectDBClauseNodeField(ObjectDBClauseParser p, int id) {
		super(p, id);
	}

}
