/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeConstant.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeConstant extends SimpleNode {
	public ObjectDBClauseNodeConstant(int id) {
		super(id);
	}

	public ObjectDBClauseNodeConstant(ObjectDBClauseParser p, int id) {
		super(p, id);
	}

}
