/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeAdd.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeAdd extends SimpleNode {
	public ObjectDBClauseNodeAdd(int id) {
		super(id);
	}

	public ObjectDBClauseNodeAdd(ObjectDBClauseParser p, int id) {
		super(p, id);
	}

}
