/**
 * ChoobStatementWrapper.
 * @author James Ross
 */
package uk.co.uwcs.choob.support;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public final class ChoobStatementWrapper implements Statement
{
	Statement stat;

	static void logSQL(final String sql) {
		System.out.println(System.currentTimeMillis() + " " + sql);
	}

	public ChoobStatementWrapper(final Statement stat) {
		this.stat = stat;
	}

	@Override public void addBatch(final String sql) throws SQLException {
		logSQL(sql);
		stat.addBatch(sql);
	}

	@Override public void cancel() throws SQLException {
		stat.cancel();
	}

	@Override public void clearBatch() throws SQLException {
		stat.clearBatch();
	}

	@Override public void clearWarnings() throws SQLException {
		stat.clearWarnings();
	}

	@Override public void close() throws SQLException {
		stat.close();
	}

	@Override public boolean execute(final String sql) throws SQLException {
		logSQL(sql);
		return stat.execute(sql);
	}

	@Override public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
		logSQL(sql);
		return stat.execute(sql, autoGeneratedKeys);
	}

	@Override public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
		logSQL(sql);
		return stat.execute(sql, columnIndexes);
	}

	@Override public boolean execute(final String sql, final String[] columnNames) throws SQLException {
		logSQL(sql);
		return stat.execute(sql, columnNames);
	}

	@Override public int[] executeBatch() throws SQLException {
		return stat.executeBatch();
	}

	@Override public ResultSet executeQuery(final String sql) throws SQLException {
		logSQL(sql);
		return stat.executeQuery(sql);
	}

	@Override public int executeUpdate(final String sql) throws SQLException {
		logSQL(sql);
		return stat.executeUpdate(sql);
	}

	@Override public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
		logSQL(sql);
		return stat.executeUpdate(sql, autoGeneratedKeys);
	}

	@Override public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
		logSQL(sql);
		return stat.executeUpdate(sql, columnIndexes);
	}

	@Override public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
		logSQL(sql);
		return stat.executeUpdate(sql, columnNames);
	}

	@Override public Connection getConnection() throws SQLException {
		return stat.getConnection();
	}

	@Override public int getFetchDirection() throws SQLException {
		return stat.getFetchDirection();
	}

	@Override public int getFetchSize() throws SQLException {
		return stat.getFetchSize();
	}

	@Override public ResultSet getGeneratedKeys() throws SQLException {
		return stat.getGeneratedKeys();
	}

	@Override public int getMaxFieldSize() throws SQLException {
		return stat.getMaxFieldSize();
	}

	@Override public int getMaxRows() throws SQLException {
		return stat.getMaxRows();
	}

	@Override public boolean getMoreResults() throws SQLException {
		return stat.getMoreResults();
	}

	@Override public boolean getMoreResults(final int current) throws SQLException {
		return stat.getMoreResults(current);
	}

	@Override public int getQueryTimeout() throws SQLException {
		return stat.getQueryTimeout();
	}

	@Override public ResultSet getResultSet() throws SQLException {
		return stat.getResultSet();
	}

	@Override public int getResultSetConcurrency() throws SQLException {
		return stat.getResultSetConcurrency();
	}

	@Override public int getResultSetHoldability() throws SQLException {
		return stat.getResultSetHoldability();
	}

	@Override public int getResultSetType() throws SQLException {
		return stat.getResultSetType();
	}

	@Override public int getUpdateCount() throws SQLException {
		return stat.getUpdateCount();
	}

	@Override public SQLWarning getWarnings() throws SQLException {
		return stat.getWarnings();
	}

	@Override public boolean isClosed() throws SQLException {
		return stat.isClosed();
	}

	@Override public boolean isPoolable() throws SQLException {
		return stat.isPoolable();
	}

	@Override public boolean isWrapperFor(final Class<?> iface) throws SQLException {
		return stat.isWrapperFor(iface);
	}

	@Override public void setCursorName(final String name) throws SQLException {
		stat.setCursorName(name);
	}

	@Override public void setEscapeProcessing(final boolean enable) throws SQLException {
		stat.setEscapeProcessing(enable);
	}

	@Override public void setFetchDirection(final int direction) throws SQLException {
		stat.setFetchDirection(direction);
	}

	@Override public void setFetchSize(final int rows) throws SQLException {
		stat.setFetchSize(rows);
	}

	@Override public void setMaxFieldSize(final int max) throws SQLException {
		stat.setMaxFieldSize(max);
	}

	@Override public void setMaxRows(final int max) throws SQLException {
		stat.setMaxRows(max);
	}

	@Override public void setPoolable(final boolean poolable) throws SQLException {
		stat.setPoolable(poolable);
	}

	@Override public void setQueryTimeout(final int seconds) throws SQLException {
		stat.setQueryTimeout(seconds);
	}

	@Override public <T> T unwrap(final Class<T> iface) throws SQLException {
		return stat.unwrap(iface);
	}

	public void closeOnCompletion() throws SQLException {
		throw new SQLException("Method stub; not available in Java 6 and not supported: closeOnCompletion");
	}

	public boolean isCloseOnCompletion() throws SQLException {
		return false;
	}
}
