/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeFieldSetList.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeFieldSetList extends SimpleNode {
  public ObjectDBClauseNodeFieldSetList(int id) {
    super(id);
  }

  public ObjectDBClauseNodeFieldSetList(ObjectDBClauseParser p, int id) {
    super(p, id);
  }

}
