/* Generated By:JJTree: Do not edit this line. ObjectDBClauseNodeMul.java */

package uk.co.uwcs.choob.support;

public class ObjectDBClauseNodeMul extends SimpleNode {
  public ObjectDBClauseNodeMul(int id) {
    super(id);
  }

  public ObjectDBClauseNodeMul(ObjectDBClauseParser p, int id) {
    super(p, id);
  }

}
