/* Generated By:JavaCC: Do not edit this line. ObjectDBClauseParserTreeConstants.java Version 4.2 */
package uk.co.uwcs.choob.support;

public interface ObjectDBClauseParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTROOT = 1;
  public int JJTADD = 2;
  public int JJTMUL = 3;
  public int JJTFUNCTION = 4;
  public int JJTCONSTANT = 5;
  public int JJTFIELD = 6;
  public int JJTEXPRESSIONLIST = 7;
  public int JJTFIELDSET = 8;
  public int JJTFIELDSETLIST = 9;


  public String[] jjtNodeName = {
    "void",
    "Root",
    "Add",
    "Mul",
    "Function",
    "Constant",
    "Field",
    "ExpressionList",
    "FieldSet",
    "FieldSetList",
  };
}
/* JavaCC - OriginalChecksum=98edd4d34fa78df6153f690d1ac2313c (do not edit this line) */
